datasets:
  dataset_name: 'mvtec_ad'  # choice ['mvtec_ad', 'visa', 'btad']
  data_path: ./data/
  class_name: 'ALL'
  img_resize: 224
  divide_num: 1
models:
  backbone_name: 'dinov2_vitb14'
  pretrained: 'openai'
  batch_size: 1
  feature_layers: [11]
  r_list: [1]
testing:
  output_dir: 'output_gui'
  vis: False
  vis_type: single_norm # choice ['single_norm', 'whole_norm']
  save_excel: False
thresholds:
  image_threshold: 9.0  # 1.0-10.0 in GUI (divided by 10 internally)
  overlay_threshold: 3.5  # 1.0-10.0 in GUI (divided by 10 internally)
device: 0


# models['backbone_name'] choice:
# ViT-B-32 | ViT-B-16 | ViT-B-16-plus-240
# ViT-L-14 | ViT-L-14-336
# dino_vitbase8 | dino_vitbase16
# dinov2_vitb14 | dinov2_vitl14

# models['pretrained'] choice:
# openai (apply to ViT-B-32, ViT-B-16, ViT-L-14 and ViT-L-14-336)
# laion400m_e31 (apply to ViT-B-32, ViT-B-16, ViT-B-16-plus-240 and ViT-L-14)
# laion400m_e32 (apply to ViT-B-32, ViT-B-16, ViT-B-16-plus-240 and ViT-L-14)
